name: Atualizar Dados do Observatório ATI

on:
  push:
    paths:
      - 'data/*.zip'
  schedule:
   - cron: '0 9 2 * *' # Roda automaticamente se você subir um ZIP novo
  workflow_dispatch: # Permite rodar manualmente apertando um botão no GitHub

# Permissão necessária para o robô fazer o git push
permissions:
  contents: write

# RESOLVE O AVISO DO NODE.JS 20 -> Força o uso do Node 24 atualizado
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  etl-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do Repositório
        uses: actions/checkout@v4

      - name: Configurar o Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar Dependências
        run: |
          pip install -r requirements.txt

      - name: Baixar ZIP e rodar o ETL
        run: |
          mesanterior=$(date -d "$(date +%Y-%m-2) -1 month" +%Y%m)
          wget -q https://dadosabertos-download.cgu.gov.br/PortalDaTransparencia/saida/servidores/$(echo $mesanterior)_Servidores_SIAPE.zip -O data/$(echo $mesanterior)_Servidores_SIAPE.zip
          python etl_atis.py

      - name: Salvar os dados processados e apagar o ZIP pesado
        run: |
                git config --local user.email "action@github.com"
                git config --local user.name "GitHub Action"
                
                # Apaga o CSV cru e o ZIP gigante para não estourar o limite do GitHub
                rm data/*_Cadastro.csv || true
                rm data/*.zip || true
                
                # FORÇA a adição dos arquivos processados (ignorando a regra do .gitignore)
                git add -f data/dados_atis.csv
                git add -f data/metadata.json
                
                # Comita e joga de volta pro repositório
                git commit -m "🤖 Update automático: Processamento dos dados mensais" || echo "Nenhuma mudança para commitar"
                git push
